### PR TITLE
Set Up React with Tailwind CSS and SCSS Modules

### PR DESCRIPTION
**Pull request by maqsudtolipov**
In this pull request:
- Setup React project via Vite with, Tailwind, SCSS, ESLint and Prettier

### CODE REVIEW

**Comment by maqsudtolipov** [comment]
🐛 BUG: Deployment failed: " Preprocessor dependency "sass-embedded" not found." Install "sass-embedded"

**Comment by wolfwalkerpd** [comment]
The error when publishing is that have you build package or you put raw file on vercel and if you did was the project done using next.js?

**Comment by maqsudtolipov** [comment]
@wolfwalkerpd It happened, when vercel ran `npm run build`. I forgot to incude the package name niside package.json.

**Comment by wolfwalkerpd** [comment]
at least you know that I don't even know how to center div :)

**Pull request merged**
